%% load data
clear;
cd(fileparts(matlab.desktop.editor.getActiveFilename));
% tisa parameters
tisa_waist = 96e-6; %m
tisa_power2intensity = 1e-6*2/pi/(tisa_waist*1e2)^2; %mW to kW cm^-2

% 804nm Feshbach molecule time scan
PA_804nm_T9_FBmol_1_dir = '..\..\202206\220601\run1_single_photon_upleg_coupling_strength_scan';
PA_804nm_T9_FBmol_1 = thermalanalysis_loader(PA_804nm_T9_FBmol_1_dir);

PA_804nm_T9_FBmol_2_dir = '..\..\202206\220601\run2_single_photon_upleg_coupling_Horizontal_polarization_transition_9_730mW';
PA_804nm_T9_FBmol_2 = thermalanalysis_loader(PA_804nm_T9_FBmol_2_dir);

PA_804nm_T9_FBmol_3_dir = '..\..\202206\220601\run3_single_photon_upleg_coupling_Horizontal_polarization_transition_9_530mW';
PA_804nm_T9_FBmol_3 = thermalanalysis_loader(PA_804nm_T9_FBmol_3_dir);

PA_804nm_T9_FBmol_4_dir = '..\..\202206\220601\run4_single_photon_upleg_coupling_Horizontal_polarization_transition_9_230mW';
PA_804nm_T9_FBmol_4 = thermalanalysis_loader(PA_804nm_T9_FBmol_4_dir);

% estimate the upleg Rabi rate 
rate_Rabi = sqrt(2*pi/(PA_804nm_T9_FBmol_1.fit_PAdecay.tau_us*1e-6)*2*pi*10e6)/2/pi/sqrt((1e3*tisa_power2intensity))

f1 = figure(1);clf;
f1.Position = [f1.Position(1) 0 500 1500];
subplot(4,1,4);hold on; box on;
errorbar(PA_804nm_T9_FBmol_1.transfer.xvals,...
    PA_804nm_T9_FBmol_1.transfer.median,...
    PA_804nm_T9_FBmol_1.transfer.errorNeg,...
    PA_804nm_T9_FBmol_1.transfer.errorPos,...
    'k.','MarkerSize',30,'CapSize',0,'LineWidth',2);
plot(PA_804nm_T9_FBmol_1.fit_PAdecay.fit_xval,...
    PA_804nm_T9_FBmol_1.fit_PAdecay.fit_yval,...
    'LineWidth',2,'color',[0 0 0 0.5]);
ylim([0 1.2]);
xlabel('time (\mus)');
ylabel('normalized molecule numer');
set(gca,'FontSize',12,'FontName','Arial');

subplot(4,1,3);hold on; box on;
errorbar(PA_804nm_T9_FBmol_2.transfer.xvals,...
    PA_804nm_T9_FBmol_2.transfer.median,...
    PA_804nm_T9_FBmol_2.transfer.errorNeg,...
    PA_804nm_T9_FBmol_2.transfer.errorPos,...
    'k.','MarkerSize',30,'CapSize',0,'LineWidth',2);
plot(PA_804nm_T9_FBmol_2.fit_PAdecay.fit_xval,...
    PA_804nm_T9_FBmol_2.fit_PAdecay.fit_yval,...
    'LineWidth',2,'color',[0 0 0 0.5]);
ylim([0 1.2]);
% xlabel('time \mus');
% ylabel('normalized fermion numer');
set(gca,'FontSize',12,'FontName','Arial',...
    'XTickLabel',[]);

subplot(4,1,2);hold on; box on;
errorbar(PA_804nm_T9_FBmol_3.transfer.xvals,...
    PA_804nm_T9_FBmol_3.transfer.median,...
    PA_804nm_T9_FBmol_3.transfer.errorNeg,...
    PA_804nm_T9_FBmol_3.transfer.errorPos,...
    'k.','MarkerSize',30,'CapSize',0,'LineWidth',2);
plot(PA_804nm_T9_FBmol_3.fit_PAdecay.fit_xval,...
    PA_804nm_T9_FBmol_3.fit_PAdecay.fit_yval,...
    'LineWidth',2,'color',[0 0 0 0.5]);
ylim([0 1.2]);
% xlabel('time \mus');
% ylabel('normalized fermion numer');
set(gca,'FontSize',12,'FontName','Arial',...
    'XTickLabel',[]);


subplot(4,1,1);hold on; box on;
errorbar(PA_804nm_T9_FBmol_4.transfer.xvals,...
    PA_804nm_T9_FBmol_4.transfer.median,...
    PA_804nm_T9_FBmol_4.transfer.errorNeg,...
    PA_804nm_T9_FBmol_4.transfer.errorPos,...
    'k.','MarkerSize',30,'CapSize',0,'LineWidth',2);
plot(PA_804nm_T9_FBmol_4.fit_PAdecay.fit_xval,...
    PA_804nm_T9_FBmol_4.fit_PAdecay.fit_yval,...
    'LineWidth',2,'color',[0 0 0 0.5]);
ylim([0 1.2]);
% xlabel('time \mus');
% ylabel('normalized fermion numer');
set(gca,'FontSize',12,'FontName','Arial',...
    'XTickLabel',[]);


f11 = figure(11);clf;
xlimit_zoom = [0 10];
f11.Position = [f11.Position(1) 0 200 800];
subplot(4,1,4);hold on; box on;
errorbar(PA_804nm_T9_FBmol_1.transfer.xvals,...
    PA_804nm_T9_FBmol_1.transfer.median,...
    PA_804nm_T9_FBmol_1.transfer.errorNeg,...
    PA_804nm_T9_FBmol_1.transfer.errorPos,...
    'k.','MarkerSize',30,'CapSize',0,'LineWidth',2);
plot(PA_804nm_T9_FBmol_1.fit_PAdecay.fit_xval,...
    PA_804nm_T9_FBmol_1.fit_PAdecay.fit_yval,...
    'LineWidth',2,'color',[0 0 0 0.5]);
ylim([0 1.2]);
xlim(xlimit_zoom);
% xlabel('time (\mus)');
% ylabel('normalized fermion numer');
set(gca,'FontSize',12,'FontName','Arial');

subplot(4,1,3);hold on; box on;
errorbar(PA_804nm_T9_FBmol_2.transfer.xvals,...
    PA_804nm_T9_FBmol_2.transfer.median,...
    PA_804nm_T9_FBmol_2.transfer.errorNeg,...
    PA_804nm_T9_FBmol_2.transfer.errorPos,...
    'k.','MarkerSize',30,'CapSize',0,'LineWidth',2);
plot(PA_804nm_T9_FBmol_2.fit_PAdecay.fit_xval,...
    PA_804nm_T9_FBmol_2.fit_PAdecay.fit_yval,...
    'LineWidth',2,'color',[0 0 0 0.5]);
ylim([0 1.2]);
xlim(xlimit_zoom);
set(gca,'FontSize',12,'FontName','Arial');

subplot(4,1,2);hold on; box on;
errorbar(PA_804nm_T9_FBmol_3.transfer.xvals,...
    PA_804nm_T9_FBmol_3.transfer.median,...
    PA_804nm_T9_FBmol_3.transfer.errorNeg,...
    PA_804nm_T9_FBmol_3.transfer.errorPos,...
    'k.','MarkerSize',30,'CapSize',0,'LineWidth',2);
plot(PA_804nm_T9_FBmol_3.fit_PAdecay.fit_xval,...
    PA_804nm_T9_FBmol_3.fit_PAdecay.fit_yval,...
    'LineWidth',2,'color',[0 0 0 0.5]);
ylim([0 1.2]);
xlim(xlimit_zoom);
set(gca,'FontSize',12,'FontName','Arial');


subplot(4,1,1);hold on; box on;
errorbar(PA_804nm_T9_FBmol_4.transfer.xvals,...
    PA_804nm_T9_FBmol_4.transfer.median,...
    PA_804nm_T9_FBmol_4.transfer.errorNeg,...
    PA_804nm_T9_FBmol_4.transfer.errorPos,...
    'k.','MarkerSize',30,'CapSize',0,'LineWidth',2);
plot(PA_804nm_T9_FBmol_4.fit_PAdecay.fit_xval,...
    PA_804nm_T9_FBmol_4.fit_PAdecay.fit_yval,...
    'LineWidth',2,'color',[0 0 0 0.5]);
ylim([0 1.2]);
xlim(xlimit_zoom);
set(gca,'FontSize',12,'FontName','Arial');






%% auxiliary functions
function output = thermalanalysis_loader(dir)

load([dir '\thermalAnalysis.mat'],'thermalAnalysis');

output = thermalAnalysis;

end